### ISSUE TITLE
Error: An option "schemaEntrypoint" is deprecated. Remove it from the config and import types from "graphql-let/__generated__/__types__".

### ISSUE THREAD

**Issue by prkagrawal** [piglovesyou/graphql-let#503]
I upgraded graphql-let to latest version and started getting this error message during nextjs build. Can't really find anything about it anywhere either.

```
[ graphql-let ] An option "schemaEntrypoint" is deprecated. Remove it from the config and import types from "graphql-let/__generated__/__types__".
Error: An option "schemaEntrypoint" is deprecated. Remove it from the config and import types from "graphql-let/__generated__/__types__".
    at buildConfig (/home/work/fe/node_modules/graphql-let/dist/lib/config.js:26:28)
    at getConfigFromContent (/home/work/fe/node_modules/graphql-let/dist/lib/config.js:53:13)
    at Object.loadConfig [as default] (/home/work/fe/node_modules/graphql-let/dist/lib/config.js:59:12)
    at async gen (/home/work/fe/node_modules/graphql-let/dist/gen.js:65:34)
[ graphql-let ] Done processing 3 GraphQL documents.

[ graphql-let ] An option "schemaEntrypoint" is deprecated. Remove it from the config and import types from "graphql-let/__generated__/__types__".
Error: An option "schemaEntrypoint" is deprecated. Remove it from the config and import types from "graphql-let/__generated__/__types__".
    at buildConfig (/home/work/fe/node_modules/graphql-let/dist/lib/config.js:26:28)
    at getConfigFromContent (/home/work/fe/node_modules/graphql-let/dist/lib/config.js:53:13)
    at Object.loadConfig [as default] (/home/work/fe/node_modules/graphql-let/dist/lib/config.js:59:12)
    at async /home/work/fe/node_modules/graphql-let/dist/loader.js:89:34
[ graphql-let ] Nothing to do. Cache was fresh.
```

**Comment by neamatmim** [comment]
Hi,
please follow the migration guide https://github.com/piglovesyou/graphql-let/releases/tag/v0.18.0

**Comment by prkagrawal** [comment]
Thanks.
