### ISSUE TITLE
Graphql-js 16.0.0 breaks graphql-let

### ISSUE THREAD

**Issue by kevinvalk** [piglovesyou/graphql-let#604]
The graphql-js release 16.0.0 (https://github.com/graphql/graphql-js/releases/tag/v16.0.0) breaks graphql-let with the following error.
```
[ graphql-let ] TypeError: visitFn.call is not a function
TypeError: visitFn.call is not a function
    at Object.visit (/node_modules/graphql/language/visitor.js:200:21)
    at Object.plugin (/node_modules/@graphql-codegen/typescript-resolvers/index.cjs.js:114:35)
    at executePlugin (/node_modules/@graphql-codegen/core/index.js:38:35)
    at /node_modules/@graphql-codegen/core/index.js:167:30
    at Array.map (<anonymous>)
    at Object.codegen (/node_modules/@graphql-codegen/core/index.js:157:54)
    at process (/node_modules/@graphql-codegen/cli/index.js:921:67)
    at Array.map (<anonymous>)
    at /node_modules/@graphql-codegen/cli/index.js:928:63
    at async Task.task (/node_modules/@graphql-codegen/cli/index.js:707:17)
[ graphql-let ] ListrError: Something went wrong
ListrError: Something went wrong
    at /node_modules/listr/index.js:102:18
    at async executeCodegen (/node_modules/@graphql-codegen/cli/index.js:945:5)
    at async Object.generate (/node_modules/@graphql-codegen/cli/index.js:1246:25)
    at async processGraphQLCodegen (/node_modules/graphql-let/dist/lib/codegen.js:140:19)
    at async Object.processCodegenForContext (/node_modules/graphql-let/dist/lib/codegen.js:168:12)
    at async gen (/node_modules/graphql-let/dist/gen.js:82:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timscott** [comment]
Is this on the roadmap?

**Comment by gastonmorixe** [comment]
I have the feeling this project has been abandoned
